modelpath: 'unet.pt'
train_h5: '/mnt/nvme2/iGlu_train_data/iglu_train_data_cropsize32_roisize4_stim_z2_filtered.h5'
batch_size: 64
learning_rate: 0.0001
num_epochs: 1
noise_center: 0.0
noise_scale: 1.5
